### PR TITLE
VBS and pitch and roll control inputs for buoyant objects in Gazebo

### PR DESCRIPTION
**Pull request by ignaciotb**

### CODE REVIEW

**Comment by nilsbore** [comment]
I know that some of you are running 16.04 and some are running 18.04. Can you test this on both before merging?

**Comment by ignaciotb** [comment]
> I know that some of you are running 16.04 and some are running 18.04. Can you test this on both before merging?

All of us are running 16.04 afaik

**Comment by nilsbore** [comment]
Ok, merging. Please add another PR if this doesn't build on anyone's computer due to missing deps etc.

**Comment by ignaciotb** [comment]
Sure

**Pull request merged**
